### PR TITLE
[EN-1388] Moves supervisor role to own repo

### PR DESCRIPTION
**Pull request by agirivera**
Story: http://jira.juwai.com/browse/EN-1388
Sub-task: http://jira.juwai.com/browse/EN-1405

- Adds galaxy tags
- No logical changes on the role from _ansible-playbooks_

How to test:

1. `git clone -b EN-1388 https://github.com/agirivera/ansible-role-supervisor.git`
1. `cd ansible-role-supervisor/tests`
1. `ansible-galaxy install -p roles -r requirements.yml`. _python27_ role will fail for the moment, run `git clone -b EN-1388 https://github.com/agirivera/ansible-role-python27.git roles/juwai.python27` instead
1. `vagrant up`

/cc @juwai/platform @tjoelsson @imlazyone Please review. Thanks.

### CODE REVIEW

**Comment by tjoelsson** [comment]
> `ansible-galaxy install juwai.common`

This will install the role globally, right?

**Comment by agirivera** [comment]
@tjoelsson: Yes, that will install globally, same as `ansible-galaxy install -r requirements.yml`. Added the said file by the way, following suggested from this [comment](https://github.com/juwai/ansible-role-python27/pull/1#issuecomment-211701101).

**Comment by tjoelsson** [comment]
I think keeping the roles contained inside the test directory is better.

**Comment by agirivera** [comment]
I see. So the step should install to the local roles directory. Got it :smile_cat: I'll update the steps for `python27` as well. Thanks.

**Comment by agirivera** [comment]
@tjoelsson Updated for local installation of roles for testing.

**Comment by tjoelsson** [comment]
👍

**Comment by imlazyone** [comment]
👍 

Although we may have some license discussion tomorrow before we merge this.

**Comment by agirivera** [comment]
@imlazyone @tjoelsson Licensing issue has been addressed. Still ok?

**Comment by tjoelsson** [comment]
👍

**Comment by imlazyone** [comment]
👍

**Comment by agirivera** [comment]
Please import to galaxy :smile_cat: Thanks.

**Comment by tjoelsson** [comment]
imported

**Pull request merged**
